"""Independent check of the pipeline, run against the real export.

1. Re-derives breach / created_shift / cause / resolver_shift for EVERY ticket with a deliberately dumb
   row-by-row implementation (stdlib csv + datetime, no pandas, written straight from the policy text) and
   compares with the pandas pipeline.
2. Hold-out test of the causal claim: fit "created with no cover -> breaches" on 2025-Q3, score 2025-Q4..2026-Q2.
3. Shows how wrong the naive report (UTC hours, resolver attribution, no dedupe) would have been.
Writes out/validation.md and out/validation_sample.csv (30 random tickets for a human to eyeball).
"""
import csv
import sys
from datetime import datetime, timedelta, date
import pandas as pd
from vireo_sla.clean import load_tickets, load_roster
from vireo_sla.attribute import add_roster_context

TARGET = {"chat": 15, "voice": 120, "social": 240, "email": 480}
TEAM = {"chat": "Chat Frontline", "social": "Chat Frontline", "email": "Email Frontline", "voice": "Voice Frontline"}
P = lambda s: datetime.strptime(s, "%Y-%m-%d %H:%M")  # noqa: E731 (export has no seconds)


def shift(dt):
    h = dt.hour
    return "Morning" if 6 <= h < 14 else "Day" if 14 <= h < 22 else "Night"


def sdate(dt):
    return (dt - timedelta(days=1) if dt.hour < 6 else dt).date()


def load_roster_rows(path):
    rows = []
    for r in csv.DictReader(open(path)):
        f = date.fromisoformat(r["from_date"]); to = date.fromisoformat(r["to_date"]) if r["to_date"] else date(2099, 12, 31)
        rows.append((r["agent_id"], r["team"], r["shift"], f, to))
    return rows


def independent(tickets_path, roster_path):
    ro = load_roster_rows(roster_path)
    seen, out = {}, {}
    for r in csv.DictReader(open(tickets_path, encoding="utf-8")):
        # keep helpdesk row when an id is in both systems
        if r["ticket_id"] in seen and r["source_system"] == "legacy_fd":
            continue
        seen[r["ticket_id"]] = 1
        c = P(r["created_at"]) + timedelta(minutes=330)
        f = P(r["first_response_at"]) + timedelta(minutes=330)
        mins = (f - c).total_seconds() / 60
        cs = shift(c); d = sdate(c)
        staffed = any(t == TEAM[r["channel"]] and s == cs and a <= d <= b for _, t, s, a, b in ro)
        rd, rs = sdate(f), None
        for aid, t, s, a, b in ro:
            if aid == r["agent_id"] and a <= rd <= b:
                rs = s
        out[r["ticket_id"]] = (mins > TARGET[r["channel"]], cs, "in-shift" if staffed else "coverage gap", rs)
    return out


def main():
    data = sys.argv[1] if len(sys.argv) > 1 else "data"
    t, _ = load_tickets(f"{data}/tickets.csv")
    t = add_roster_context(t, load_roster(f"{data}/agents.csv"))
    ind = independent(f"{data}/tickets.csv", f"{data}/agents.csv")
    L = ["# Validation results (generated by tests/validate.py)\n"]

    mism = {"breach": 0, "created_shift": 0, "cause": 0, "resolver_shift": 0}
    bad = []
    for r in t.itertuples():
        b, cs, ca, rs = ind[r.ticket_id]
        for k, mine, theirs in (("breach", r.breach, b), ("created_shift", r.created_shift, cs),
                                ("cause", r.cause, ca), ("resolver_shift", r.resolver_shift, rs)):
            if mine != theirs:
                mism[k] += 1; bad.append((r.ticket_id, k))
    L.append(f"## 1. Independent re-implementation, all {len(t):,} tickets\n")
    L.append(f"Mismatches: {mism}. Tickets in independent path: {len(ind):,} (pipeline: {len(t):,}).\n")
    L.append("This proves the code does what the rules say. It does NOT prove the rules are right (both are mine); see 2.\n")

    # 2. hold-out
    tr = t[(t.created_at_ist >= "2025-07-01") & (t.created_at_ist < "2025-10-01")]
    te = t[t.created_at_ist >= "2025-10-01"]
    rule = tr.groupby(["channel", "cause"]).breach.mean().gt(0.5)  # predict breach if train rate > 50%
    pred = te.set_index(["channel", "cause"]).index.map(lambda k: bool(rule.get(k, False)))
    act = te.breach.values
    tp = int(((pred == True) & act).sum()); fp = int(((pred == True) & ~act).sum()); fn = int(((pred == False) & act).sum())  # noqa
    tn = int(((pred == False) & ~act).sum())  # noqa
    L.append("## 2. Hold-out: does 'no cover at creation' explain breaches out of sample?\n")
    L.append(f"Rule learned on 2025-Q3 only (predict breach when channel+cause breached >50% in train). Scored on {len(te):,} tickets, 2025-Q4 to 2026-Q2.\n")
    L.append(f"- accuracy {(tp+tn)/len(te):.1%}, precision {tp/max(tp+fp,1):.1%}, recall {tp/max(tp+fn,1):.1%}\n")
    L.append(f"- confusion: TP {tp}, FP {fp}, FN {fn}, TN {tn}\n")
    L.append(f"- breaches the rule cannot explain (FN): {fn} of {int(act.sum())} = {fn/act.sum():.1%}. These are ordinary in-shift breaches (~9% floor) and the half of overnight EMAIL tickets that breach.\n")
    L.append(f"- overnight email is the weak spot: {int(((te.channel=='email')&(te.cause=='coverage gap')).sum())} tickets, "
             f"{te[(te.channel=='email')&(te.cause=='coverage gap')].breach.mean():.0%} breach - the rule predicts 'no breach' so it misses those breaches, and the exact hour decides (8h target vs 06:00 start).\n")
    L.append(f"- placebo: before 2025-07-01 gap tickets = {int(((t.created_at_ist<'2025-07-01')&(t.cause=='coverage gap')).sum())} (both are 30 Jun night); breach rate {t[t.created_at_ist<'2025-07-01'].breach.mean():.1%}. In-shift breach rate by quarter is flat: "
             + ", ".join(f"{k} {v:.1%}" for k, v in t[t.cause == 'in-shift'].groupby(t.created_at_ist.dt.to_period('Q').astype(str)).breach.mean().items()) + ".\n")

    # 3. naive report
    raw = pd.read_csv(f"{data}/tickets.csv", parse_dates=["created_at", "first_response_at"])
    raw["breach"] = (raw.first_response_at - raw.created_at).dt.total_seconds() / 60 > raw.channel.map(TARGET)
    H = lambda h: 'Morning' if 6 <= h < 14 else 'Day' if 14 <= h < 22 else 'Night'  # noqa
    naive_shift = raw.created_at.dt.hour.map(H)
    L.append("## 3. What the naive report would have said\n")
    L.append(f"- No dedupe: {len(raw):,} rows vs {len(t):,} real tickets; breaches counted {int(raw.breach.sum()):,} vs {int(t.breach.sum()):,}.\n")
    ist_shift = (raw.created_at + pd.Timedelta(minutes=330)).dt.hour.map(H)
    L.append(f"- Treating UTC as IST puts {(naive_shift != ist_shift).mean():.0%} of tickets in the wrong shift.\n")
    hd = t[t.created_at_ist >= "2025-07-01"].groupby("resolver_shift").breach.sum()
    L.append(f"- Charging breaches to the resolver's shift (helpdesk default), Jul 2025-Jun 2026: {hd.to_dict()}. "
             f"Of Morning's, {int(((t.resolver_shift=='Morning')&(t.cause=='coverage gap')&t.breach).sum())} were created overnight with nobody rostered.\n")
    L.append(f"- Agent view: {int((t[t.cause=='coverage gap'].groupby('agent_id').breach.sum() > 0).sum())} agents carry breaches from the coverage gap in their names.\n")

    # sample for eyeballing
    s = t.sample(30, random_state=7)[["ticket_id", "channel", "created_at", "created_at_ist", "first_response_at_ist", "frt_min",
                                     "target_min", "breach", "created_shift", "cause", "agent_id", "resolver_name", "resolver_shift"]]
    s.to_csv("out/validation_sample.csv", index=False)
    open("out/validation.md", "w", encoding="utf-8").write("\n".join(L))
    print("\n".join(L))
    return 1 if any(mism.values()) else 0


if __name__ == "__main__":
    sys.exit(main())
